const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.join(__dirname,'..'),source=fs.readFileSync(path.join(root,'carabiner.js'),'utf8');
function fixture(reduce=false){
  const el=()=>({style:{},attrs:{},events:{},setAttribute(k,v){this.attrs[k]=v;},addEventListener(k,v){this.events[k]=v;}});
  const control=el(),buttons=[el(),el(),el()],refs=[el(),el(),el()],body=el(),spine=el(),tube=el(),removedSpine=el(),label=el();
  const results={};for(const n of ['volume','stress','deflection','volume-change','stress-change','deflection-change'])results[n]=el();
  let globalPause=false,callback,next=0,intersection,mutations=[];
  const ambient={classList:{contains:()=>globalPause}},classes=new Set();
  const demo={dataset:{},classList:{add:k=>classes.add(k)},querySelector:s=>s.startsWith('[data-result=')?results[s.match(/"([^"]+)"/)[1]]:({'.carabiner-toggle':control,'[data-carabiner-body]':body,'[data-carabiner-spine]':spine,'[data-removed-tube]':tube,'[data-removed-spine]':removedSpine,'[data-design-label]':label}[s]),querySelectorAll:s=>s==='.carabiner-stage'?buttons:refs};
  const doc={hidden:false,events:{},documentElement:{classList:{contains:()=>false}},querySelector:s=>s==='.carabiner-demo'?demo:ambient,addEventListener(k,v){this.events[k]=v;}};
  const media={matches:reduce,addEventListener(k,v){this.change=v;}};
  class IO{constructor(fn){intersection=fn;}observe(){}}class MO{constructor(fn){mutations.push(fn);}observe(){}}
  vm.runInNewContext(source,{document:doc,window:{IntersectionObserver:IO},IntersectionObserver:IO,MutationObserver:MO,matchMedia:()=>media,requestAnimationFrame:fn=>{callback=fn;return ++next;},cancelAnimationFrame:()=>{callback=null;}});
  return {control,buttons,refs,body,spine,tube,removedSpine,label,results,demo,media,doc,classes,tick:t=>{const fn=callback;callback=null;if(fn)fn(t);},running:()=>!!callback,intersect:v=>intersection([{isIntersecting:v}]),globalPause:v=>{globalPause=v;mutations[0]();}};
}
let count=0;const test=(name,fn)=>{fn();count++;console.log('PASS '+name);};
test('static fallback is labeled and data remains readable without script',()=>{const h=fs.readFileSync(path.join(root,'projects/carabiner-fea.html'),'utf8');assert.match(h,/aria-labelledby="carabiner-title carabiner-description"/);assert.match(h,/not Ansys playback/);assert.match(h,/not a climbing or life-safety rating/);assert.match(h,/1734.4 mm³/);});
test('initial baseline enhances controls without removed material',()=>{const f=fixture();assert.equal(f.control.hidden,false);assert.equal(f.demo.dataset.step,'0');assert.equal(f.tube.style.opacity,'0');assert.equal(f.removedSpine.style.opacity,'0');assert.ok(f.running());});
test('spine comparison displays exact reported values and calculated percentages',()=>{const f=fixture();f.buttons[1].events.click();assert.equal(f.results.volume.textContent,'1627.8 mm³');assert.equal(f.results.stress.textContent,'358.76 MPa');assert.equal(f.results.deflection.textContent,'1.79 mm');assert.equal(f.results['volume-change'].textContent,'6.1% less volume');assert.equal(f.results['stress-change'].textContent,'2.6% higher peak stress');assert.equal(f.spine.attrs['stroke-width'],'28');assert.equal(f.tube.style.opacity,'0');});
test('whole tube comparison uses its own data and removal extent',()=>{const f=fixture();f.buttons[2].events.click();assert.equal(f.results.volume.textContent,'1251.5 mm³');assert.equal(f.results.stress.textContent,'416.18 MPa');assert.equal(f.results.deflection.textContent,'1.94 mm');assert.equal(f.results['volume-change'].textContent,'27.8% less volume');assert.equal(f.results['stress-change'].textContent,'19.0% higher peak stress');assert.equal(f.body.attrs['stroke-width'],'32');assert.equal(f.removedSpine.style.opacity,'0');});
test('manual design selection pauses and reveals matching report image',()=>{const f=fixture();f.buttons[1].events.click();assert.equal(f.running(),false);assert.equal(f.refs[1].hidden,false);assert.equal(f.refs[0].hidden,true);assert.equal(f.control.textContent,'Play Animation');f.control.events.click();assert.ok(f.running());});
test('reduced motion permits static design comparison',()=>{const f=fixture(true);assert.equal(f.running(),false);assert.equal(f.control.disabled,true);f.buttons[2].events.click();assert.equal(f.demo.dataset.step,'2');assert.equal(f.body.attrs['stroke-width'],'32');});
test('hidden tab and offscreen states stop frame work',()=>{const f=fixture();f.doc.hidden=true;f.doc.events.visibilitychange();assert.equal(f.running(),false);f.doc.hidden=false;f.doc.events.visibilitychange();assert.ok(f.running());f.intersect(false);assert.equal(f.running(),false);});
test('global pause preserves the visitor-selected pause',()=>{const f=fixture();f.globalPause(true);assert.equal(f.running(),false);f.globalPause(false);assert.ok(f.running());f.buttons[1].events.click();f.globalPause(true);f.globalPause(false);assert.equal(f.running(),false);});
test('comparison loops through all three alternatives',()=>{const f=fixture();f.tick(0);for(let t=100;t<=12100;t+=100){f.tick(t);if(t%4000===100)assert.equal(f.demo.dataset.step,String(Math.floor(t/4000)%3));}});
test('animation data agrees with the case table and references use mesh images',()=>{const h=fs.readFileSync(path.join(root,'projects/carabiner-fea.html'),'utf8');for(const [i,row]of [[0,['1734.4','349.82','1.63']],[1,['1627.8','358.76','1.79']],[2,['1251.5','416.18','1.94']]]){const f=fixture();f.buttons[i].events.click();for(const value of row)assert.ok(h.includes('<td>'+value+'</td>'));assert.equal(f.results.volume.textContent,row[0]+' mm³');}for(const n of ['standard','reduced-spine','whole-tube'])assert.ok(fs.existsSync(path.join(root,'images/carabiner-'+n+'.png')));assert.match(h,/mesh images show geometry only/);});
console.log(`${count} carabiner illustration checks passed.`);
